In [ ]:
import numpy as np


Execute the cell below before starting the 1st mission.

In [ ]:
array_1 = np.array([10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54,
       35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])

array_1

array([10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54,
       35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])

# Mission 1

Using Numpy, how many axes `array_1` has ?




In [10]:
print(f"Soit juste {array_1.ndim} axes ")
print(np.shape(array_1))
print(" array_1 got only one axes but 32 element in it")

Soit juste 1 axes 
(32,)
 array_1 got only one axes but 32 element in it


Still using Numpy, how many dimensions `array_1` has?

In [11]:
print(f"Soit juste {array_1.ndim} dimensions")

Soit juste 1 dimensions


Display the first element of `array_1`

In [13]:
print(f" the first element of array_1 is {array_1[0] }")

 the first element of array_1 is 10


# Mission 2

Modify, using a `numpy` method, the `array_1` object to be an object that has two axes, including 1 row and 32 columns.  
Save it under the variable `array_2`.

In [15]:
array_2 = array_1.reshape(1,32)
array_2

array([[10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54,
        54, 35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35]])

Now, modify `array_1` into an object that has 32 rows and only 1 column.  
Save it under the variable `array_3`.

In [16]:
array_3 = array_1.reshape(32,1)
array_3

array([[10],
       [40],
       [45],
       [ 5],
       [66],
       [91],
       [43],
       [75],
       [40],
       [28],
       [55],
       [45],
       [31],
       [71],
       [67],
       [54],
       [54],
       [35],
       [64],
       [27],
       [12],
       [93],
       [17],
       [91],
       [50],
       [57],
       [74],
       [61],
       [86],
       [20],
       [36],
       [35]])

Access the first element of `array_2`, then of `array_3`.  
What do you notice?  
Why ?

In [32]:

print(array_2[0])
print(array_3[0])
print(array_2[0, 0])
print(array_3[0, 0])


[10 40 45  5 66 91 43 75 40 28 55 45 31 71 67 54 54 35 64 27 12 93 17 91
 50 57 74 61 86 20 36 35]
[10]
10
10


answer  : une vue 1x32 du tableau pour array_2[0] et print(array_3[0]) sous forme de tableau 1x1, car chaque "ligne" de array_3 contient un seul élément.

# Mission 3

Access the value that is at index 3 of array `array_2`.  
Do it with Numpy way, then with Python way.

In [37]:
ar4 = array_2[0,3]
print(ar4)

liste4 = list(array_2)
print(liste4[0][3])

5
5


Access the value which is at index 3 of array `array_3` in Numpy.

In [39]:
ar5 = array_3[3,0]
ar5

5

# Mission 4

Reshape `array_1` to be a 4-row, 8-column array,
rather than a 32-element vector.  
Save your array under the variable `array_4`.

In [40]:
array_4 = array_1.reshape(4, 8)
array_4

array([[10, 40, 45,  5, 66, 91, 43, 75],
       [40, 28, 55, 45, 31, 71, 67, 54],
       [54, 35, 64, 27, 12, 93, 17, 91],
       [50, 57, 74, 61, 86, 20, 36, 35]])

Access for each row, the values ​​of the columns which have the index 1 to 2 included.

In [41]:
array_4[:,1:3]

array([[40, 45],
       [28, 55],
       [35, 64],
       [57, 74]])

Access for rows at position 1 and 2 inclusive, the values ​​of all columns.

In [42]:
array_4[1:3,:]

array([[40, 28, 55, 45, 31, 71, 67, 54],
       [54, 35, 64, 27, 12, 93, 17, 91]])

Access for the rows which have the index 2 to 3 inclusive, to the values ​​of the columns which have the index 3 to 5 inclusive.

In [43]:
array_4[2:4,3:6]

array([[27, 12, 93],
       [61, 86, 20]])

Select the first column, as well as the columns whose index is a multiple of 2.

In [44]:
array_4[:,::2]

array([[10, 45, 66, 43],
       [40, 55, 31, 67],
       [54, 64, 12, 17],
       [50, 74, 86, 36]])

Select columns whose index is odd.

In [45]:
array_4[:,1::2]

array([[40,  5, 91, 75],
       [28, 45, 71, 54],
       [35, 27, 93, 91],
       [57, 61, 20, 35]])

# Mission 5

Reshape your `array_1` vector into a 3-dimensional array.
Your 3-dimensional array should have 2 matrices, each of which has 4 rows and 4 columns.
Save your array under the variable `array_5`.

In [46]:
array_5 = array_1.reshape(2,4,4)
array_5

array([[[10, 40, 45,  5],
        [66, 91, 43, 75],
        [40, 28, 55, 45],
        [31, 71, 67, 54]],

       [[54, 35, 64, 27],
        [12, 93, 17, 91],
        [50, 57, 74, 61],
        [86, 20, 36, 35]]])

Use the .shape attribute to observe the number of axes for `array_5`.

In [47]:
array_5.shape

(2, 4, 4)

Select all values ​​from the first matrix.

In [48]:
array_5[0,:,:]

array([[10, 40, 45,  5],
       [66, 91, 43, 75],
       [40, 28, 55, 45],
       [31, 71, 67, 54]])

Access for both matrices,
to the values ​​corresponding to the rows at index 1 and to the columns that have positions 3 and 4.

In [52]:
array_5[:,1,2:4]

array([[43, 75],
       [17, 91]])

Access row values ​​at positions 2 to 3,
columns at indexes 1 to 3 included for the second matrix only.

In [54]:
array_5[1,2:4,1:4]

array([[57, 74, 61],
       [20, 36, 35]])


Reshape `array_5` so that we have 8 rows and 4 columns.

In [55]:
array_5 = array_5.reshape(8,4)
print(array_5)

[[10 40 45  5]
 [66 91 43 75]
 [40 28 55 45]
 [31 71 67 54]
 [54 35 64 27]
 [12 93 17 91]
 [50 57 74 61]
 [86 20 36 35]]
