# NumPy : Introduction

**NumPy allows you to manipulate data in the form of an array.**

**Complete the missions below using NumPy.**

In [2]:
import numpy as np # Here we rename numpy as np, it's shorter, and everybody does that

# Mission 1 : Display the version of NumPy you are running (as each library, you can use np.__version__)
print(np.__version__)


1.26.4


In [3]:
# Mission 2 : Create a NumPy array with a length of 3, that contains this 3 floats: 0.8, 0.6, 0.4
# Expected result: array([0.8, 0.6, 0.4])
arrayFloatant = np.array([0.8, 0.6,0.4])
print(arrayFloatant)

[0.8 0.6 0.4]


In [4]:
# Mission 3 : Create a function that uses the np.random.random() function to return an array with 10 random elements,
# all of which must be greater than 0.25 and less than 1.0

# Example of expected result: array([0.3897948 , 0.82850041, 0.5499838 , 0.81940137, 0.92175875, 0.89634373, 0.26821861, 0.72376496, 0.81098623, 0.28192741])
def function():
  ara = np.random.random(10) # 10 elment entre 0.0 et 1.0
  ara = 0.25 + ara * (1.0 - 0.25) #respect of range
  return ara
print(f"array({function()}")



array([0.81369843 0.79266614 0.48441302 0.61541624 0.82895105 0.73258865
 0.85266697 0.85662019 0.46298408 0.62561254]


In [16]:
# Mission 4 : What does the np.empty() method do? Don't just copy the documentation, explain in your own words here
#np.empty() :retourn un tab videavec une forme ,on peut choisir le type de  données


In [17]:
# Mission 5 : Create an array filled with only zeros. You can choose the length of this array.
array0 = np.zeros(3)
print(array0)
#zeros(x) est la bonne fonction

[0. 0. 0.]


In [14]:
# Mission 6 : Create an array filled with 10 random integers.
aleatoire = np.random.randint(10,size = 10)
print(aleatoire)

[7 6 1 0 7 3 9 2 3 4]


In [18]:
# Mission 7 : Create an array that contains 50 values randomly selected only from these numbers: 0, 1, 2, 3, 4, 5, 6, 7.
tab = np.random.randint(0,8,50)
print(tab)
# debut 0, fin non compris dedans 8 nb elem 50

[2 7 6 1 3 0 1 0 6 2 2 6 6 2 2 5 5 4 5 6 0 6 1 1 1 5 1 0 4 6 3 4 7 2 1 6 4
 0 2 0 2 4 5 3 1 5 5 3 5 0]
